"""Change scruture

Revision ID: 7438d7d983d2
Revises: e09112e556c3
Create Date: 2026-02-09 11:46:06.407217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7438d7d983d2'
down_revision: Union[str, Sequence[str], None] = 'e09112e556c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'is_active')
    # ### end Alembic commands ###
