"""rename expires_time to expires_at

Revision ID: 53aaad7a8849
Revises: 7438d7d983d2
Create Date: 2026-02-09 11:49:14.750980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53aaad7a8849'
down_revision: Union[str, Sequence[str], None] = '7438d7d983d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    op.drop_column('tokens', 'expires_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('expires_time', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'expires_at')
    # ### end Alembic commands ###
