"""Remember me Added

Revision ID: 7ae1e97a482b
Revises: 4d3619aab06f
Create Date: 2026-02-09 11:24:15.264610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae1e97a482b'
down_revision: Union[str, Sequence[str], None] = '4d3619aab06f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('remember', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remember')
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    # ### end Alembic commands ###
